config/routes.rb
Rails.application.routes.draw do
  resources :interests

  namespace :api do 
    namespace :v1 do 
     resources :interests, only: [:index, :create, :destroy, :update]
    end 
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest.rb
class Interest < ApplicationRecord
  validates :postcode, presence: true
end

app/controllers/api/v1/interests_controller.rb
class Api::V1::InterestsController < ApplicationController
  def index
    render json: Interest.all
  end

  def create
    interest = Interest.create(interest_params)
    render json: interest
  end

  private

  def interest_params
    params.require(:interest).permit(:first_name, :postcode, :email, :tel)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def new
    @interest = Interest.new
  end

  def create
    @interest = Interest.new(interest_params)

    if @interest.save
      redirect_to interest_path(@interest.id)
    else
      render 'new'
    end
  end

  def show
    @interest = Interest.find(params[:id])
  end

  private

  def interest_params
    params.require(:interest).permit(:first_name, :postcode, :email, :tel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/home/index.html.erb
<div style="margin-left: 30px;">
  <%= react_component "App" %>
  <h2>About Us</h2>
</div>

app/views/interests/new.html.erb
<div class="container">
  <div class="block">
    <h1 class="title">Register your interest</h1>
    <%= form_for @interest do |form| %>
      <div class="field">
        <%= form.label "First Name", class: "label" %>
        <div class="control">
          <%= form.text_field :first_name, class: "input"%>
        </div>
      </div>
      <div class="field">
        <%= form.label "Postcode", class: "label" %>
        <div class="control">
          <%= form.text_field :postcode, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "Email", class: "label" %>
        <div class="control">
          <%= form.email_field :email, class: "input" %>
        </div>
      </div>
      <div class="field">
          <%= form.label "Telephone Number", class: "label" %>
        <div class="control">
          <%= form.text_field :tel, class: "input" %>
        </div>
      </div><br>
      <div>
        <%= form.submit "Submit", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/interests/show.html.erb
<div style="margin-left: 30px;">
  <h3>Thank you for registering your interest, <%= @interest.first_name %>.</h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UdderlessCustomerWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('TM-logo.gif') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/"><%= image_tag("TM-logo.gif") %></a>
  <form class="form-inline">
    <% if current_page?(root_path) %> 
      <div>
        <%= link_to('Register Interest', new_interest_path, :class => 'btn btn-large btn-primary') %>
      </div>
    <% else %> 
      <div>
        <%= link_to('About Us', root_path, :class => 'btn btn-large btn-primary') %>
      </div>
    <% end %>
  </form>
</nav>